//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.CalculatorServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html", ConfigurationName="CalculatorServices.CalculatorService")]
    public interface CalculatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Ad" +
            "d", ReplyAction="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Ad" +
            "dResponse")]
        double Add(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Ad" +
            "d", ReplyAction="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Ad" +
            "dResponse")]
        System.Threading.Tasks.Task<double> AddAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Su" +
            "btract", ReplyAction="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Su" +
            "btractResponse")]
        double Subtract(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Su" +
            "btract", ReplyAction="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Su" +
            "btractResponse")]
        System.Threading.Tasks.Task<double> SubtractAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Mu" +
            "ltiply", ReplyAction="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Mu" +
            "ltiplyResponse")]
        double Multiply(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Mu" +
            "ltiply", ReplyAction="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Mu" +
            "ltiplyResponse")]
        System.Threading.Tasks.Task<double> MultiplyAsync(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Di" +
            "vide", ReplyAction="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Di" +
            "videResponse")]
        double Divide(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Di" +
            "vide", ReplyAction="http://www.cnblogs.com/artech/archive/2007/02/26/656901.html/CalculatorService/Di" +
            "videResponse")]
        System.Threading.Tasks.Task<double> DivideAsync(double x, double y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculatorServiceChannel : WCFClient.CalculatorServices.CalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorServiceClient : System.ServiceModel.ClientBase<WCFClient.CalculatorServices.CalculatorService>, WCFClient.CalculatorServices.CalculatorService {
        
        public CalculatorServiceClient() {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Add(double x, double y) {
            return base.Channel.Add(x, y);
        }
        
        public System.Threading.Tasks.Task<double> AddAsync(double x, double y) {
            return base.Channel.AddAsync(x, y);
        }
        
        public double Subtract(double x, double y) {
            return base.Channel.Subtract(x, y);
        }
        
        public System.Threading.Tasks.Task<double> SubtractAsync(double x, double y) {
            return base.Channel.SubtractAsync(x, y);
        }
        
        public double Multiply(double x, double y) {
            return base.Channel.Multiply(x, y);
        }
        
        public System.Threading.Tasks.Task<double> MultiplyAsync(double x, double y) {
            return base.Channel.MultiplyAsync(x, y);
        }
        
        public double Divide(double x, double y) {
            return base.Channel.Divide(x, y);
        }
        
        public System.Threading.Tasks.Task<double> DivideAsync(double x, double y) {
            return base.Channel.DivideAsync(x, y);
        }
    }
}
